package com.hikvision.netsdk.linux.x86;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class NET_DVR_DEVICEINFO_V30 extends Structure {
	/** \u5e8f\u5217\u53f7 */
	public byte[] sSerialNumber = new byte[48];
	/** \u62a5\u8b66\u8f93\u5165\u4e2a\u6570 */
	public byte byAlarmInPortNum;
	/** \u62a5\u8b66\u8f93\u51fa\u4e2a\u6570 */
	public byte byAlarmOutPortNum;
	/** \u786c\u76d8\u4e2a\u6570 */
	public byte byDiskNum;
	/** \u8bbe\u5907\u7c7b\u578b, 1:DVR 2:ATM DVR 3:DVS ...... */
	public byte byDVRType;
	/** \u6a21\u62df\u901a\u9053\u4e2a\u6570 */
	public byte byChanNum;
	/** \u8d77\u59cb\u901a\u9053\u53f7,\u4f8b\u5982DVS-1,DVR - 1 */
	public byte byStartChan;
	/** \u8bed\u97f3\u901a\u9053\u6570 */
	public byte byAudioChanNum;
	/** \u6700\u5927\u6570\u5b57\u901a\u9053\u4e2a\u6570 */
	public byte byIPChanNum;
	/** \u96f6\u901a\u9053\u7f16\u7801\u4e2a\u6570 //2010-01-16 */
	public byte byZeroChanNum;
	/** \u4e3b\u7801\u6d41\u4f20\u8f93\u534f\u8bae\u7c7b\u578b 0-private, 1-rtsp */
	public byte byMainProto;
	/** \u5b50\u7801\u6d41\u4f20\u8f93\u534f\u8bae\u7c7b\u578b0-private, 1-rtsp */
	public byte bySubProto;
	/** \u80fd\u529b\uff0c\u4f4d\u4e0e\u7ed3\u679c\u4e3a0\u8868\u793a\u4e0d\u652f\u6301\uff0c1\u8868\u793a\u652f\u6301\uff0c */
	public byte bySupport;
	/**
	 * bySupport & 0x80, \u8868\u793a\u652f\u6301rtp over rtsp<br>
	 * \u80fd\u529b\u96c6\u6269\u5145\uff0c\u4f4d\u4e0e\u7ed3\u679c\u4e3a0\u8868\u793a\u4e0d\u652f\u6301\uff0c1\u8868\u793a\u652f\u6301
	 */
	public byte bySupport1;
	/** bySupport1 & 0x10, \u8868\u793a\u662f\u5426\u652f\u6301\u591a\u78c1\u76d8\u6570\uff08\u8d85\u8fc733\u4e2a\uff09 */
	public byte byRes1;
	/** \u8bbe\u5907\u578b\u53f7 */
	public short wDevType;
	/** \u4fdd\u7559 */
	public byte[] byRes2 = new byte[16];
	public NET_DVR_DEVICEINFO_V30() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("sSerialNumber", "byAlarmInPortNum", "byAlarmOutPortNum", "byDiskNum", "byDVRType", "byChanNum", "byStartChan", "byAudioChanNum", "byIPChanNum", "byZeroChanNum", "byMainProto", "bySubProto", "bySupport", "bySupport1", "byRes1", "wDevType", "byRes2");
	}
	public static class ByReference extends NET_DVR_DEVICEINFO_V30 implements Structure.ByReference {
		
	}

    public static class ByValue extends NET_DVR_DEVICEINFO_V30 implements Structure.ByValue {
		
	}
}
