package com.hikvision.netsdk.linux.x86;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class NET_DVR_CLIENTINFO extends Structure {
	/** \u901a\u9053\u53f7 */
	public int lChannel;
	/** \u6700\u9ad8\u4f4d(31)\u4e3a0\u8868\u793a\u4e3b\u7801\u6d41\uff0c\u4e3a1\u8868\u793a\u5b50\uff0c0\uff0d30\u4f4d\u8868\u793a\u7801\u6d41\u8fde\u63a5\u65b9\u5f0f: 0\uff1aTCP\u65b9\u5f0f,1\uff1aUDP\u65b9\u5f0f,2\uff1a\u591a\u64ad\u65b9\u5f0f,3 - RTP\u65b9\u5f0f\uff0c4-RTP/RTSP,5-RSTP/HTTP */
	public int lLinkMode;
	/** \u64ad\u653e\u7a97\u53e3\u7684\u53e5\u67c4,\u4e3aNULL\u8868\u793a\u4e0d\u64ad\u653e\u56fe\u8c61 */
	public int hPlayWnd;
	/** \u591a\u64ad\u7ec4\u5730\u5740 */
	public Pointer sMultiCastIP;
	public NET_DVR_CLIENTINFO() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("lChannel", "lLinkMode", "hPlayWnd", "sMultiCastIP");
	}
	public NET_DVR_CLIENTINFO(int lChannel, int lLinkMode, int hPlayWnd, Pointer sMultiCastIP) {
		super();
		this.lChannel = lChannel;
		this.lLinkMode = lLinkMode;
		this.hPlayWnd = hPlayWnd;
		this.sMultiCastIP = sMultiCastIP;
	}
	public static class ByReference extends NET_DVR_CLIENTINFO implements Structure.ByReference {
		
	}

    public static class ByValue extends NET_DVR_CLIENTINFO implements Structure.ByValue {
		
	}
}
