package com.dahua.netsdk.linux;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class NET_TIME extends Structure {
	/** \u5e74 */
	public int dwYear;
	/** \u6708 */
	public int dwMonth;
	/** \u65e5 */
	public int dwDay;
	/** \u65f6 */
	public int dwHour;
	/** \u5206 */
	public int dwMinute;
	/** \u79d2 */
	public int dwSecond;
	public NET_TIME() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("dwYear", "dwMonth", "dwDay", "dwHour", "dwMinute", "dwSecond");
	}
	public NET_TIME(int dwYear, int dwMonth, int dwDay, int dwHour, int dwMinute, int dwSecond) {
		super();
		this.dwYear = dwYear;
		this.dwMonth = dwMonth;
		this.dwDay = dwDay;
		this.dwHour = dwHour;
		this.dwMinute = dwMinute;
		this.dwSecond = dwSecond;
	}
	public static class ByReference extends NET_TIME implements Structure.ByReference {
		
	};
	public static class ByValue extends NET_TIME implements Structure.ByValue {
		
	};
}
